//ASSIGNMENT-2 QUESTION-6

LDA B210 
MOV B,A
LDA B200  /
ANA B //A and B
MOV D,A //STORING A AND B RESULT IN REGISTER D
LDA B230  
MOV C,A
ANA B  //B AND C
MOV E,A  //STORING B AND C RESULT IN REGISTER E
MOV A,B
ORA C   //B OR C
ANA E   //(B AND C)AND(B OR C)
CMA //COMPLIMENT
ORA D
STA B240
HLT
